### ISSUE TITLE
License.md Missing

### ISSUE THREAD

**Issue by mohamdiveten** [JoeMayo/csharp-nine-cookbook#1]

**Comment by JoeMayo** [comment]
Hi @mohamdiveten 

That's added. Additionally, O'Reilly has guidance on code usage in the book Preface, under the Using Code Examples section.

Thanks,

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by mohamdiveten** [comment]
Well noted @JoeMayo.
Regards.
@mohamdiveten
