### ISSUE TITLE
It should be recommended to install the NuGet package "IronPython.StdLib"

### ISSUE THREAD

**Issue by TWINSBaltiya** [JoeMayo/csharp-nine-cookbook#4]
Since the "IronPython" NuGet package is installed without "IronPython.StdLib", then it is advisable to recommend readers to install an additional NuGet package "IronPython.StdLib". Then you can remove the addition of the path to the libraries from the Python code: "import sys
sys.path.append(path)".
This will avoid a mismatch between the IronPython and Python versions, which leads to a compilation error.:
Microsoft.Scripting.SyntaxErrorException: "invalid syntax".

**Comment by JoeMayo** [comment]
Thank you for pointing this out. I've added it to errata and will do a PR to update projects.

**Comment by JoeMayo** [comment]
Errata added to the book here: https://www.oreilly.com/catalog/errata.csp?isbn=0636920467434
